import type { Metadata } from "next";
import {Provider} from 'react-redux'

// store
import {store} from '../store'
import "./globals.css";


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <Provider store={store}>
    <html lang="en">
      <body>
        {children}
      </body>
    </html>
    </Provider>
  );
}
